[package]
name = "slapd"
version = "0.1.0"
authors = ["William Brown <william@blackhats.net.au>"]
rust-version = "1.70"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fernet = "0.1"
